### ISSUE TITLE
npm install error 

### ISSUE THREAD

**Issue by prafful1234** [hyperledger-labs/convector#21]
npm v - 6.4.1
node v -  8.11.0
os - ubantu 18.04.1 LTS
After creating a new convector project by following steps at 
--> https://worldsibu.github.io/convector/modules/getting_started.html
on installing npm in my test project I get this error.

----------------------------------------------------------------------------------------------------------------------

/home/engineer/testing/node_modules/ts-simple-ast/dist/manipulation/manipulations/doManipulation.js:14
        throw new errors.InvalidOperationError(err.message + "\n" +
        ^

Error: Error replacing tree: Should not have new children left over.
-- Details --
Path: /home/engineer/testing/packages/testing-chain-cc/client/testing-chain.controller.ts
Text: "...nds ConvectorController {\n  @Invokable()\n  public async create(\n    @Param(TestingChain)\n    testing\n\n  public name = 'testing-chain';\n-chain: TestingChain\n  ) {\n    await testing-chain.save();\n  }\n}"
    at InvalidOperationError.BaseError [as constructor] (/home/engineer/testing/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
    at new InvalidOperationError (/home/engineer/testing/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
    at Object.doManipulation (/home/engineer/testing/node_modules/ts-simple-ast/dist/manipulation/manipulations/doManipulation.js:14:15)
    at insertIntoBracesOrSourceFile (/home/engineer/testing/node_modules/ts-simple-ast/dist/manipulation/manipulations/insertion.js:101:22)
    at Object.insertIntoBracesOrSourceFileWithGetChildren (/home/engineer/testing/node_modules/ts-simple-ast/dist/manipulation/manipulations/insertion.js:140:5)
    at ClassDeclaration.insertProperties (/home/engineer/testing/node_modules/ts-simple-ast/dist/compiler/class/ClassDeclaration.js:288:31)
    at ClassDeclaration.addProperties (/home/engineer/testing/node_modules/ts-simple-ast/dist/compiler/class/ClassDeclaration.js:271:21)
    at ClassDeclaration.addProperty (/home/engineer/testing/node_modules/ts-simple-ast/dist/compiler/class/ClassDeclaration.js:264:21)
    at Object.<anonymous> (/home/engineer/testing/node_modules/@worldsibu/convector-core-adapter/dist/src/generate-interface.js:32:12)
    at Module._compile (module.js:652:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testing-chain-cc@0.1.0 client:generate: `generate-controller-interface -c TestingChainController`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testing-chain-cc@0.1.0 client:generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/engineer/.npm/_logs/2018-12-03T07_35_16_803Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testing-chain-cc@0.1.0 build: `npm run clean && npm run client:generate && tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testing-chain-cc@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/engineer/.npm/_logs/2018-12-03T07_35_16_819Z-debug.log
lerna info lifecycle testing-chain-cc@0.1.0~prepare: Failed to exec prepare script
lerna ERR! lifecycle "prepare" errored in "testing-chain-cc", exiting 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testing@0.1.0 lerna:install: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testing@0.1.0 lerna:install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/engineer/.npm/_logs/2018-12-03T07_35_16_837Z-debug.log
ERROR: "lerna:install" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testing@0.1.0 install: `npm-run-all -s lerna:install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testing@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/engineer/.npm/_logs/2018-12-03T07_35_16_858Z-debug.log

**Comment by walmon** [comment]
Hi @prafful1234 just to close and keep the history of the solution, as discussed in the [Discord channel](https://t.co/7MSSj4yo9o) the solution was to update your Node version from `8.11.0` to `8.11.4`.

Thanks!

**Comment by prafful1234** [comment]
thanks, I tried to install on multiple node version using NPM as well but it just supports 8.11.4 version on both Ubuntu and Arch Linux, 
can you please update it on this tutorial page as well, please. 
--> https://worldsibu.github.io/convector/modules/getting_started.html
would be really helpful for beginners thanks, appreciate.
